sudo: false
language: go
addons:
  apt:
    update: true
    packages:
    - docker-ce
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
  matrix:
    - GO111MODULE=on
    - GO111MODULE=off
go:
  - "1.11.x"
  - "1.12.x"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && ! $(which nc)     ]] ; then sudo apt-get install -y netcat ; fi
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose --version
  - docker-compose -f docker-compose.yml pull
  - docker-compose -f docker-compose.yml up -d
  - while ! nc -z localhost 3306; do sleep 1; done
  - while ! nc -z localhost 27017; do sleep 1; done
install:
  - go get github.com/mattn/go-sqlite3
  - go get ./...
script:
  - go test -race -v ./...
