sudo: false
language: go
env:
- GO111MODULE=on
- GO111MODULE=off
go:
  - "1.11.x"
  - "1.12.x"
services:
- mysql
- mongodb
install:
- go get ./...
script:
- go test -race -v ./...

#- go get github.com/google/uuid
#- go get github.com/go-sql-driver/mysql
#- go get github.com/jinzhu/gorm
#- go get gopkg.in/mgo.v2
#- go get github.com/gorilla/websocket
