sudo: false
language: go
go:
  - 1.7
services:
  - mysql
  - mongodb
install:
  - go get github.com/google/uuid
  - go get github.com/go-sql-driver/mysql
  - go get github.com/jinzhu/gorm
  - go get gopkg.in/mgo.v2
  - go get github.com/gorilla/websocket
