on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest]
    name: Run ${{ matrix.go-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Setup Go ${{ matrix.go-version }}"
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Start docker-compose"
      run: docker-compose -f docker-compose.yml up -d
    - name: Wait for infrastructure
      run: |
        while ! nc -z localhost 3306; do sleep 1; done
        while ! nc -z localhost 27017; do sleep 1; done
    - name: "Run tests"
      run: go test -race -v ./...
