on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    name: Run ${{ matrix.go-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - name: "Setup Go ${{ matrix.go-version }}"
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Start docker-compose"
      run: docker-compose -f docker-compose.yml up -d
    - name: "Run tests"
      run: go test -race -v ./...
